baseURL = "https://minidomo.github.io/rhe-306-presentation/public/"
languageCode = "en-us"
title = "Transparency with low-SES students | RHE 306"

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = false
style = "tango"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
history = true
